---
- name: Restore AAP
  hosts: localhost
  become: true
  vars:
    aap_setup_working_dir: /root/ansible-automation-platform-installer/
    aap_restore_location: "{{playbook_dir}}/aap-backup-latest.tar.gz"
  roles:
    - infra.aap_utilities.aap_restore